name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-vps:

    runs-on: ubuntu-latest

    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/chat.risiverse.com/
            sudo git reset --hard HEAD
            sudo git pull
            sudo npm install
            sudo npm run build